# Numpy进阶 Homework

2021.4.13

**本次作业将完成numpy迭代器和ufunc的基本操作** 

### 1.单维迭代器
分别以C,F以及默认顺序遍历a矩阵，观察输出结果（*提示：`np.nditer()`函数包含参数 `order`*）

In [1]:
import numpy as np
a = np.arange(6).reshape(2, 3)

## TODO
for x in np.nditer(a):
    print(x,end=',')
print()
for x in np.nditer(a,order='C'):
    print(x,end=',')
print()
for x in np.nditer(a,order='F'):
    print(x,end=',')

0,1,2,3,4,5,
0,1,2,3,4,5,
0,3,1,4,2,5,

**用两种方法实现：**利用迭代器遍历矩阵a，要求返回值顺序为`0,3,1,4,2,5`

In [2]:
## TODO
for x in np.nditer(a,order='F'):
    print(x,end=',')
print()
for x in np.nditer(a.T,order='C'):
    print(x,end=',')

0,3,1,4,2,5,
0,3,1,4,2,5,

### 2.外部循环
在使用外部循环`external_loop`模式的基础上，**用两种方法实现：**将a矩阵各元素扩大为原来2倍*（提示：C，F及默认顺序任选其二）*

In [3]:
a = np.arange(8).reshape(2, 4)

## TODO
for x in np.nditer(a,flags=['external_loop'],op_flags=["readwrite"]):
    x[...]=x*2
a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [4]:
a = np.arange(8).reshape(2, 4)

## TODO
for x in np.nditer(a,flags=['external_loop'],order='C',op_flags=["readwrite"]):
    x[...]=x*2
a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

定义矩阵$A^{m*1}, B^{1*n}$，令$C^{m*n} = AB$，则C为秩一矩阵，要求利用numpy迭代器的`multi_index`模式，实现求C的过程

In [5]:
A = np.arange(5).reshape(5,1) + 1
B = np.arange(3).reshape(1,3) + 1

## TODO
C=np.empty((5,3))
it=np.nditer([A,B],flags=['multi_index'])
while not it.finished:
    C[it.multi_index]=it[0]*it[1]
    it.iternext()
C

array([[ 1.,  2.,  3.],
       [ 2.,  4.,  6.],
       [ 3.,  6.,  9.],
       [ 4.,  8., 12.],
       [ 5., 10., 15.]])

### 3.U_function
自定义一个numpy的ufunc函数，实现`z = 2*x*x+12*y*y`的计算任务，并与利用`numpy`函数实现该任务比较计算时长

In [6]:
x = list(range(10000))
y = list(range(10000))

## TODO
import time
def my_cal(x,y):
    return 2*x*x+12*y*y
start=time.time()
z1=np.frompyfunc(my_cal,2,1)(x,y)
end1=time.time()
z2=np.add(np.square(x)*2,12*np.square(y))
end2=time.time()
print(end1-start,end2-end1)

0.008962392807006836 0.0043680667877197266
